
import Footer from "./componentes/Footer";
import Navbar from "./componentes/Navbar";
import "./globals.css";
import EcommerceProvider from "../context/Contex";

export const metadata = {
  title: "Camaleon",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", 
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <EcommerceProvider>
        <header>
          <Navbar />
        </header>
        {children}
        <footer>
          <Footer />
        </footer>
        </EcommerceProvider>
      </body>
    </html>
  );
}
